// ============================================================
// MOCK DATA - CareerOS Mobile App
// ============================================================

export const CURRENT_USER = {
  id: 'usr_001',
  auId: 'AU2021CS045',
  name: 'Arjun Sharma',
  email: 'arjun.sharma@university.edu',
  role: 'student',
  avatar: null,
};

export const STUDENT_PROFILE = {
  id: 'sp_001',
  userId: 'usr_001',
  name: 'Arjun Sharma',
  auId: 'AU2021CS045',
  department: 'Computer Science & Engineering',
  batchYear: 2021,
  currentSemester: 7,
  cgpa: 8.4,
  careerGoal: 'placement',
  profilePhotoUrl: null,
  linkedinUrl: 'https://linkedin.com/in/arjunsharma',
  githubUrl: 'https://github.com/arjunsharma',
  phone: '+91 98765 43210',
  city: 'Hyderabad',
  bio: 'Passionate full-stack developer with a keen interest in AI/ML. Looking for opportunities in top-tier tech companies.',
};

export const ACADEMIC_RECORDS = [
  { semester: 1, gpa: 8.2, subjects: [
    { code: 'CS101', name: 'Programming Fundamentals', grade: 'A', marks: 87, maxMarks: 100, attendance: 92 },
    { code: 'MA101', name: 'Engineering Mathematics I', grade: 'B+', marks: 78, maxMarks: 100, attendance: 88 },
    { code: 'PH101', name: 'Engineering Physics', grade: 'A', marks: 85, maxMarks: 100, attendance: 90 },
    { code: 'EN101', name: 'Technical English', grade: 'A+', marks: 92, maxMarks: 100, attendance: 95 },
  ]},
  { semester: 2, gpa: 8.5, subjects: [
    { code: 'CS201', name: 'Data Structures', grade: 'A+', marks: 94, maxMarks: 100, attendance: 93 },
    { code: 'CS202', name: 'Digital Logic Design', grade: 'A', marks: 88, maxMarks: 100, attendance: 89 },
    { code: 'MA201', name: 'Engineering Mathematics II', grade: 'A', marks: 85, maxMarks: 100, attendance: 91 },
    { code: 'CS203', name: 'Object Oriented Programming', grade: 'A+', marks: 96, maxMarks: 100, attendance: 94 },
  ]},
  { semester: 3, gpa: 8.1, subjects: [
    { code: 'CS301', name: 'Algorithms & Complexity', grade: 'A', marks: 84, maxMarks: 100, attendance: 87 },
    { code: 'CS302', name: 'Database Systems', grade: 'A', marks: 86, maxMarks: 100, attendance: 90 },
    { code: 'CS303', name: 'Operating Systems', grade: 'B+', marks: 78, maxMarks: 100, attendance: 82 },
    { code: 'CS304', name: 'Computer Networks', grade: 'A', marks: 83, maxMarks: 100, attendance: 88 },
  ]},
  { semester: 4, gpa: 8.6, subjects: [
    { code: 'CS401', name: 'Machine Learning', grade: 'A+', marks: 93, maxMarks: 100, attendance: 94 },
    { code: 'CS402', name: 'Web Technologies', grade: 'A+', marks: 95, maxMarks: 100, attendance: 92 },
    { code: 'CS403', name: 'Software Engineering', grade: 'A', marks: 87, maxMarks: 100, attendance: 90 },
    { code: 'CS404', name: 'Computer Architecture', grade: 'A', marks: 85, maxMarks: 100, attendance: 88 },
  ]},
  { semester: 5, gpa: 8.3, subjects: [
    { code: 'CS501', name: 'Deep Learning', grade: 'A', marks: 86, maxMarks: 100, attendance: 91 },
    { code: 'CS502', name: 'Cloud Computing', grade: 'A', marks: 84, maxMarks: 100, attendance: 89 },
    { code: 'CS503', name: 'Distributed Systems', grade: 'B+', marks: 79, maxMarks: 100, attendance: 85 },
    { code: 'CS504', name: 'Cybersecurity Fundamentals', grade: 'A', marks: 88, maxMarks: 100, attendance: 92 },
  ]},
  { semester: 6, gpa: 8.7, subjects: [
    { code: 'CS601', name: 'System Design', grade: 'A+', marks: 92, maxMarks: 100, attendance: 93 },
    { code: 'CS602', name: 'DevOps & CI/CD', grade: 'A+', marks: 94, maxMarks: 100, attendance: 91 },
    { code: 'CS603', name: 'Mobile App Development', grade: 'A', marks: 88, maxMarks: 100, attendance: 90 },
    { code: 'CS604', name: 'Natural Language Processing', grade: 'A', marks: 86, maxMarks: 100, attendance: 88 },
  ]},
];

export const SKILLS = [
  { id: 'sk_001', name: 'React.js', category: 'technical', proficiency: 'advanced', score: 85, verified: true },
  { id: 'sk_002', name: 'Node.js', category: 'technical', proficiency: 'advanced', score: 80, verified: true },
  { id: 'sk_003', name: 'Python', category: 'technical', proficiency: 'expert', score: 92, verified: true },
  { id: 'sk_004', name: 'Machine Learning', category: 'technical', proficiency: 'intermediate', score: 72, verified: false },
  { id: 'sk_005', name: 'PostgreSQL', category: 'technical', proficiency: 'intermediate', score: 70, verified: true },
  { id: 'sk_006', name: 'Docker', category: 'technical', proficiency: 'intermediate', score: 65, verified: false },
  { id: 'sk_007', name: 'React Native', category: 'technical', proficiency: 'intermediate', score: 68, verified: false },
  { id: 'sk_008', name: 'TypeScript', category: 'technical', proficiency: 'intermediate', score: 72, verified: false },
  { id: 'sk_009', name: 'Communication', category: 'soft', proficiency: 'advanced', score: 80, verified: false },
  { id: 'sk_010', name: 'Problem Solving', category: 'soft', proficiency: 'expert', score: 90, verified: false },
  { id: 'sk_011', name: 'Team Leadership', category: 'soft', proficiency: 'intermediate', score: 70, verified: false },
  { id: 'sk_012', name: 'System Design', category: 'domain', proficiency: 'intermediate', score: 68, verified: false },
  { id: 'sk_013', name: 'DSA', category: 'domain', proficiency: 'advanced', score: 82, verified: true },
];

export const PROJECTS = [
  {
    id: 'prj_001',
    title: 'AI-Powered Resume Builder',
    description: 'A full-stack web app using GPT-4 to generate and optimize resumes based on job descriptions. Features ATS scoring, keyword optimization, and export.',
    technologies: ['React', 'Node.js', 'OpenAI API', 'PostgreSQL'],
    githubLink: 'https://github.com/arjunsharma/ai-resume-builder',
    startDate: '2024-01-15',
    endDate: '2024-03-20',
    isTeamProject: false,
    status: 'completed',
  },
  {
    id: 'prj_002',
    title: 'Real-Time Collaborative Code Editor',
    description: 'Browser-based IDE with real-time collaboration using WebSockets. Supports 15+ languages, syntax highlighting, and video call integration.',
    technologies: ['React', 'Socket.io', 'Express', 'Monaco Editor', 'WebRTC'],
    githubLink: 'https://github.com/arjunsharma/collab-code',
    startDate: '2023-08-01',
    endDate: '2023-11-30',
    isTeamProject: true,
    status: 'completed',
  },
  {
    id: 'prj_003',
    title: 'Smart Campus Navigation App',
    description: 'React Native app with indoor navigation, AR markers, and real-time crowd density mapping for university campuses.',
    technologies: ['React Native', 'ARKit', 'Google Maps API', 'Firebase'],
    githubLink: 'https://github.com/arjunsharma/smart-campus',
    startDate: '2024-06-01',
    endDate: null,
    isTeamProject: true,
    status: 'ongoing',
  },
];

export const CERTIFICATIONS = [
  {
    id: 'cert_001',
    name: 'AWS Solutions Architect Associate',
    organization: 'Amazon Web Services',
    issueDate: '2024-02-15',
    expiryDate: '2027-02-15',
    credentialUrl: 'https://aws.amazon.com/certification',
    verified: true,
  },
  {
    id: 'cert_002',
    name: 'TensorFlow Developer Certificate',
    organization: 'Google',
    issueDate: '2023-09-10',
    expiryDate: '2026-09-10',
    credentialUrl: 'https://tensorflow.org/certificate',
    verified: true,
  },
  {
    id: 'cert_003',
    name: 'Meta Frontend Developer Professional Certificate',
    organization: 'Meta / Coursera',
    issueDate: '2023-05-20',
    expiryDate: null,
    credentialUrl: 'https://coursera.org/certificates/meta-frontend',
    verified: true,
  },
];

export const INTERNSHIPS = [
  {
    id: 'int_001',
    companyName: 'TCS Digital',
    role: 'Full Stack Developer Intern',
    durationMonths: 3,
    stipend: 15000,
    description: 'Developed microservices for the banking digital transformation project. Built REST APIs using Spring Boot and React frontend.',
    skillsUsed: ['React', 'Spring Boot', 'MySQL', 'Docker'],
    startDate: '2024-05-01',
    endDate: '2024-07-31',
  },
  {
    id: 'int_002',
    companyName: 'Wipro AI Labs',
    role: 'ML Research Intern',
    durationMonths: 2,
    stipend: 12000,
    description: 'Worked on NLP pipeline for sentiment analysis of customer reviews. Improved model accuracy by 12% using BERT fine-tuning.',
    skillsUsed: ['Python', 'PyTorch', 'BERT', 'NLP', 'Hugging Face'],
    startDate: '2023-12-01',
    endDate: '2024-01-31',
  },
];

export const CAREER_ROADMAP = {
  goalType: 'placement',
  progressPercentage: 62,
  currentMilestoneIndex: 4,
  milestones: [
    { id: 1, title: 'Master Data Structures & Algorithms', durationWeeks: 8, status: 'completed', skills: ['Arrays', 'Linked Lists', 'Trees', 'Graphs', 'DP'], assessment: 'Complete 150 LeetCode problems', order: 1 },
    { id: 2, title: 'Build Core Projects Portfolio', durationWeeks: 6, status: 'completed', skills: ['Full Stack Dev', 'System Design', 'APIs'], assessment: '3 significant projects on GitHub', order: 2 },
    { id: 3, title: 'Aptitude & Reasoning Prep', durationWeeks: 4, status: 'completed', skills: ['Quantitative', 'Logical', 'Verbal'], assessment: 'Score 80%+ in mock tests', order: 3 },
    { id: 4, title: 'System Design Fundamentals', durationWeeks: 4, status: 'completed', skills: ['Scalability', 'Databases', 'Caching', 'Load Balancing'], assessment: 'Design 5 real-world systems', order: 4 },
    { id: 5, title: 'Advanced ML & AI Projects', durationWeeks: 6, status: 'in_progress', skills: ['ML', 'Deep Learning', 'NLP', 'Computer Vision'], assessment: 'Deploy 2 ML models to production', order: 5 },
    { id: 6, title: 'Mock Interview Practice', durationWeeks: 4, status: 'pending', skills: ['Technical Interview', 'Behavioral', 'Communication'], assessment: '20 mock interviews completed', order: 6 },
    { id: 7, title: 'Resume & LinkedIn Optimization', durationWeeks: 2, status: 'pending', skills: ['Personal Branding', 'ATS Optimization'], assessment: 'Profile reviewed by mentor', order: 7 },
    { id: 8, title: 'Company Research & Applications', durationWeeks: 4, status: 'pending', skills: ['Job Search', 'Networking', 'Applications'], assessment: 'Applied to 50+ companies', order: 8 },
  ],
};

export const PLACEMENT_PREDICTION = {
  predictionScore: 78,
  predictedSalaryBand: '8-15 LPA',
  predictedCompanyTier: 'tier2',
  interviewReadinessScore: 71,
  weakAreas: ['System Design Depth', 'Behavioral Interviews', 'Advanced SQL'],
  strongAreas: ['DSA', 'Python/ML', 'Project Experience', 'Communication'],
  companyMatches: [
    { company: 'TCS Digital', tier: 'tier2', probability: 92, package: '7-9 LPA' },
    { company: 'Infosys Specialist', tier: 'tier2', probability: 88, package: '6-9 LPA' },
    { company: 'Wipro Turbo', tier: 'tier2', probability: 85, package: '6.5-9 LPA' },
    { company: 'Accenture Technology', tier: 'tier2', probability: 82, package: '7-10 LPA' },
    { company: 'Cognizant Digital', tier: 'tier2', probability: 80, package: '6-8 LPA' },
    { company: 'Flipkart SDE-1', tier: 'tier1', probability: 45, package: '20-30 LPA' },
    { company: 'Amazon SDE-1', tier: 'tier1', probability: 38, package: '25-40 LPA' },
  ],
  recommendations: [
    { area: 'System Design', action: 'Complete Grokking System Design course and practice 10 design problems', priority: 'high' },
    { area: 'Behavioral Interviews', action: 'Prepare STAR format answers for 20 common behavioral questions', priority: 'high' },
    { area: 'Advanced SQL', action: 'Complete SQLZoo and practice 30 advanced query problems', priority: 'medium' },
    { area: 'LeetCode Hard', action: 'Solve 20 more LeetCode hard problems focusing on DP and Graphs', priority: 'medium' },
    { area: 'Open Source', action: 'Contribute to 2 open source projects to boost GitHub profile', priority: 'low' },
  ],
  factors: {
    positive: [
      { factor: 'CGPA 8.4', impact: '+12 points', description: 'Above average academic performance' },
      { factor: '2 Internships', impact: '+15 points', description: 'Strong industry exposure' },
      { factor: 'AWS Certification', impact: '+8 points', description: 'Industry recognized credential' },
      { factor: '3 Major Projects', impact: '+10 points', description: 'Solid project portfolio' },
      { factor: 'Python Expert Level', impact: '+7 points', description: 'High demand technical skill' },
    ],
    negative: [
      { factor: 'System Design Gap', impact: '-8 points', description: 'Below average system design score' },
      { factor: 'No Mock Interviews', impact: '-6 points', description: 'Interview practice milestone pending' },
      { factor: 'Low Docker/DevOps', impact: '-4 points', description: 'Cloud skills need improvement' },
    ],
  },
};

export const SKILL_SCORES = {
  industryReadinessScore: 74,
  breakdown: {
    technicalSkills: { score: 78, weight: 0.35, label: 'Technical Skills' },
    projectDepth: { score: 75, weight: 0.25, label: 'Project Depth' },
    certifications: { score: 80, weight: 0.15, label: 'Certifications' },
    internships: { score: 70, weight: 0.15, label: 'Internship Experience' },
    githubActivity: { score: 60, weight: 0.10, label: 'GitHub Activity' },
  },
  domainScores: {
    webDev: 82,
    aiMl: 75,
    data: 68,
    devOps: 55,
    security: 48,
    core: 85,
  },
  primaryDomain: 'Web Development',
  batchRank: 12,
  batchSize: 120,
  percentile: 90,
  skillGaps: [
    { skill: 'Kubernetes', required: 60, current: 20, priority: 'high', forGoal: 'placement' },
    { skill: 'GraphQL', required: 55, current: 25, priority: 'medium', forGoal: 'placement' },
    { skill: 'Redis', required: 50, current: 30, priority: 'medium', forGoal: 'placement' },
    { skill: 'System Design', required: 80, current: 68, priority: 'high', forGoal: 'placement' },
    { skill: 'Behavioral Interview', required: 75, current: 45, priority: 'high', forGoal: 'placement' },
  ],
};

export const JOB_MARKET_DATA = {
  trendingSkills: [
    { rank: 1, skill: 'Generative AI', demandScore: 98, jobCount: 45200, avgSalary: '18-35 LPA', growth: '+145%', trend: 'up' },
    { rank: 2, skill: 'LLM Engineering', demandScore: 96, jobCount: 32100, avgSalary: '20-40 LPA', growth: '+130%', trend: 'up' },
    { rank: 3, skill: 'Kubernetes', demandScore: 92, jobCount: 56700, avgSalary: '15-28 LPA', growth: '+45%', trend: 'up' },
    { rank: 4, skill: 'React.js', demandScore: 90, jobCount: 78400, avgSalary: '8-20 LPA', growth: '+22%', trend: 'up' },
    { rank: 5, skill: 'Python', demandScore: 89, jobCount: 95600, avgSalary: '8-25 LPA', growth: '+28%', trend: 'up' },
    { rank: 6, skill: 'AWS', demandScore: 88, jobCount: 67800, avgSalary: '12-30 LPA', growth: '+35%', trend: 'up' },
    { rank: 7, skill: 'TypeScript', demandScore: 85, jobCount: 45300, avgSalary: '10-22 LPA', growth: '+40%', trend: 'up' },
    { rank: 8, skill: 'Data Engineering', demandScore: 84, jobCount: 38900, avgSalary: '14-28 LPA', growth: '+38%', trend: 'up' },
    { rank: 9, skill: 'DevOps/MLOps', demandScore: 82, jobCount: 41200, avgSalary: '12-25 LPA', growth: '+30%', trend: 'up' },
    { rank: 10, skill: 'Go (Golang)', demandScore: 78, jobCount: 22400, avgSalary: '15-30 LPA', growth: '+52%', trend: 'up' },
    { rank: 11, skill: 'Rust', demandScore: 72, jobCount: 14500, avgSalary: '18-35 LPA', growth: '+68%', trend: 'up' },
    { rank: 12, skill: 'Node.js', demandScore: 80, jobCount: 56200, avgSalary: '8-20 LPA', growth: '+15%', trend: 'stable' },
    { rank: 13, skill: 'SQL', demandScore: 86, jobCount: 88700, avgSalary: '7-18 LPA', growth: '+10%', trend: 'stable' },
    { rank: 14, skill: 'Cybersecurity', demandScore: 85, jobCount: 34600, avgSalary: '12-30 LPA', growth: '+42%', trend: 'up' },
    { rank: 15, skill: 'Blockchain', demandScore: 65, jobCount: 18200, avgSalary: '15-35 LPA', growth: '-12%', trend: 'down' },
  ],
  salaryBenchmarks: [
    { role: 'Software Engineer (SDE-1)', tier1: '25-40 LPA', tier2: '8-15 LPA', tier3: '4-8 LPA' },
    { role: 'ML Engineer', tier1: '30-50 LPA', tier2: '12-20 LPA', tier3: '6-12 LPA' },
    { role: 'Data Scientist', tier1: '20-35 LPA', tier2: '10-18 LPA', tier3: '5-10 LPA' },
    { role: 'DevOps Engineer', tier1: '22-38 LPA', tier2: '10-16 LPA', tier3: '5-9 LPA' },
    { role: 'Frontend Developer', tier1: '20-32 LPA', tier2: '7-14 LPA', tier3: '4-8 LPA' },
    { role: 'Backend Developer', tier1: '22-38 LPA', tier2: '8-15 LPA', tier3: '4-8 LPA' },
    { role: 'Full Stack Developer', tier1: '24-40 LPA', tier2: '8-16 LPA', tier3: '4-9 LPA' },
    { role: 'Product Manager', tier1: '30-60 LPA', tier2: '12-22 LPA', tier3: '6-12 LPA' },
  ],
};

export const MENTORS = [
  {
    id: 'men_001',
    name: 'Dr. Priya Reddy',
    title: 'Senior ML Engineer',
    company: 'Google India',
    expertise: ['Machine Learning', 'Python', 'Data Science', 'Career Guidance'],
    experience: 8,
    bio: 'IIT Bombay alumni with 8+ years in ML. Passionate about helping students break into top tech companies.',
    rating: 4.9,
    reviewCount: 47,
    menteeCount: 3,
    maxMentees: 5,
    matchScore: 92,
    goalAlignment: 'placement',
    available: true,
    avatar: null,
    sessionCount: 0,
  },
  {
    id: 'men_002',
    name: 'Rahul Mehta',
    title: 'Staff Software Engineer',
    company: 'Microsoft',
    expertise: ['System Design', 'Full Stack', 'Interview Prep', 'DSA'],
    experience: 10,
    bio: 'Ex-Amazon, now at Microsoft. Helped 50+ students crack FAANG interviews. Specializes in system design and coding rounds.',
    rating: 4.8,
    reviewCount: 63,
    menteeCount: 4,
    maxMentees: 5,
    matchScore: 88,
    goalAlignment: 'placement',
    available: true,
    avatar: null,
    sessionCount: 0,
  },
  {
    id: 'men_003',
    name: 'Ananya Singh',
    title: 'Product Manager',
    company: 'Flipkart',
    expertise: ['Product Management', 'Strategy', 'Analytics', 'Career Switch'],
    experience: 6,
    bio: 'CS grad turned PM. Helps technical students transition to product roles at top startups and e-commerce companies.',
    rating: 4.7,
    reviewCount: 28,
    menteeCount: 2,
    maxMentees: 4,
    matchScore: 71,
    goalAlignment: 'placement',
    available: true,
    avatar: null,
    sessionCount: 0,
  },
  {
    id: 'men_004',
    name: 'Prof. Suresh Kumar',
    title: 'Associate Professor & GATE Expert',
    company: 'IIT Hyderabad',
    expertise: ['GATE Preparation', 'Algorithms', 'Theory of Computation', 'Research'],
    experience: 15,
    bio: 'GATE ranker and academic mentor. Specializes in higher education guidance and competitive exam preparation.',
    rating: 4.9,
    reviewCount: 82,
    menteeCount: 5,
    maxMentees: 8,
    matchScore: 65,
    goalAlignment: 'gate',
    available: false,
    avatar: null,
    sessionCount: 0,
  },
];

export const MY_MENTORS = [
  {
    relationId: 'rel_001',
    mentor: MENTORS[0],
    status: 'active',
    startedAt: '2024-09-01',
    nextSession: '2024-12-10T15:00:00',
    totalSessions: 6,
    notes: 'Focus on ML interview prep and portfolio review',
  },
];

export const WELLNESS_DATA = {
  consistencyScore: 72,
  currentStreak: 8,
  longestStreak: 21,
  activeDaysThisMonth: 18,
  totalDaysThisMonth: 28,
  burnoutRisk: 'low',
  avgDailyMinutes: 95,
  weeklyActivity: [
    { day: 'Mon', minutes: 120, activities: ['DSA Practice', 'Project Work'] },
    { day: 'Tue', minutes: 90, activities: ['Online Course', 'LeetCode'] },
    { day: 'Wed', minutes: 60, activities: ['Mock Interview'] },
    { day: 'Thu', minutes: 150, activities: ['Project Work', 'System Design Study'] },
    { day: 'Fri', minutes: 45, activities: ['Resume Update'] },
    { day: 'Sat', minutes: 180, activities: ['Hackathon', 'Open Source'] },
    { day: 'Sun', minutes: 30, activities: ['Light Reading'] },
  ],
  recentActivities: [
    { id: 'act_001', type: 'dsa_practice', label: 'DSA Practice', date: '2024-12-08', duration: 90, notes: 'Solved 3 medium graph problems' },
    { id: 'act_002', type: 'project_work', label: 'Project Work', date: '2024-12-08', duration: 60, notes: 'Added authentication to campus app' },
    { id: 'act_003', type: 'online_course', label: 'Online Course', date: '2024-12-07', duration: 45, notes: 'Completed System Design module 4' },
    { id: 'act_004', type: 'mock_interview', label: 'Mock Interview', date: '2024-12-06', duration: 60, notes: 'Practiced with peer - got feedback on communication' },
    { id: 'act_005', type: 'dsa_practice', label: 'DSA Practice', date: '2024-12-05', duration: 120, notes: 'DP patterns revision - 5 problems' },
  ],
  activityTypes: [
    { id: 'dsa_practice', label: 'DSA Practice', icon: 'code-slash', color: '#6366F1' },
    { id: 'project_work', label: 'Project Work', icon: 'construct', color: '#10B981' },
    { id: 'online_course', label: 'Online Course', icon: 'school', color: '#F59E0B' },
    { id: 'mock_interview', label: 'Mock Interview', icon: 'people', color: '#3B82F6' },
    { id: 'resume_prep', label: 'Resume Prep', icon: 'document-text', color: '#8B5CF6' },
    { id: 'networking', label: 'Networking', icon: 'share-social', color: '#EC4899' },
    { id: 'reading', label: 'Reading/Research', icon: 'book', color: '#14B8A6' },
    { id: 'other', label: 'Other', icon: 'ellipsis-horizontal', color: '#9CA3AF' },
  ],
};

export const NOTIFICATIONS = [
  { id: 'notif_001', type: 'milestone_reminder', title: 'Milestone Due Soon', message: 'Your ML Projects milestone is due in 5 days. Keep up the momentum!', time: '2 hours ago', read: false, icon: 'flag' },
  { id: 'notif_002', type: 'encouragement', title: '8-Day Streak! 🔥', message: 'Amazing consistency! You have studied 8 days in a row. Keep it going!', time: '6 hours ago', read: false, icon: 'flame' },
  { id: 'notif_003', type: 'mentor_message', title: 'Message from Dr. Priya', message: 'Great progress on your ML projects! Let\'s discuss deployment strategies in our next session.', time: '1 day ago', read: true, icon: 'person' },
  { id: 'notif_004', type: 'risk_alert', title: 'Skill Gap Alert', message: 'System Design score is below your goal requirement. Consider adding more practice sessions.', time: '2 days ago', read: true, icon: 'warning' },
  { id: 'notif_005', type: 'market_update', title: 'Market Insight', message: 'GenAI skill demand rose 145% this quarter. Your ML skills are highly relevant!', time: '3 days ago', read: true, icon: 'trending-up' },
];

export const ADMIN_BATCH_STATS = {
  batchId: 'CSE_2021',
  batchName: 'CSE Batch 2021',
  totalStudents: 120,
  placementReadyCount: 68,
  atRiskCount: 18,
  averageCGPA: 7.8,
  averageSkillScore: 62,
  placedCount: 0,
  domainDistribution: {
    webDev: 38,
    aiMl: 22,
    data: 18,
    devOps: 12,
    security: 8,
    other: 22,
  },
  topSkillGaps: [
    { skill: 'System Design', studentsNeeding: 72 },
    { skill: 'Behavioral Interviews', studentsNeeding: 65 },
    { skill: 'Advanced SQL', studentsNeeding: 58 },
    { skill: 'Kubernetes', studentsNeeding: 89 },
    { skill: 'TypeScript', studentsNeeding: 54 },
  ],
  predictionDistribution: {
    tier1: 8,
    tier2: 42,
    tier3: 52,
    uncertain: 18,
  },
};
